### ISSUE TITLE
Remove question mark from filename

### ISSUE THREAD

**Issue by pm64** [sw-yx/ai-notes#13]
Question marks in filenames are disallowed in NTFS, so Windows users are unable to clone this repo.

Consider renaming the file "blog ideas/What is Instruction Tuning?.md"

**Comment by sw-yx** [comment]
ok wil do

**Comment by pm64** [comment]
Thanks for maintaining this awesome repo. Sorry to bug about this again, but the file "blog ideas/what is the AI native stack?.md" contains a question mark. Would you mind renaming the file?

**Comment by swyxio** [comment]
ok @pm64 done
