### ISSUE TITLE
AI Hackathon Stack - Not sure which category to add under

### ISSUE THREAD

**Issue by yairhaimo** [sw-yx/ai-notes#22]
Hi,

I created https://client.aigur.dev which is an opensource library to compose and invoke Generative AI pipelines but it doesnt really fit under any specific criteria. Any thoughts where should I add it under?

**Comment by sw-yx** [comment]
hi! no not really. there are many pipeline/workflow style things - i'll just decline this for now but reconsider in future as i understand hackathon needs. thanks!
