### ISSUE TITLE
interesting resource: “State of AI Report”

### ISSUE THREAD

**Issue by phineas-pta** [sw-yx/ai-notes#29]
**disclaimer**: i'm not affiliated with the authors or any of their works

since 2018 “State of AI Report” has centralised and summarised principal AI progress

all reports are publicly available under CC-4.0 here: https://www.stateof.ai/

in my opinion, this should be add to “Top AI Reads” > “Intermediate Reads”

**Comment by sw-yx** [comment]
ok good call. adding
